package com.example.adventuregame.Model;

import java.util.Random;

public class RandomGenerator {

    private static final Random RANDOM = new Random();
    private static final String[] NAMES = {
            "John", "Jane", "Michael", "Emily", "David", "Emma", "Chris", "Olivia", "James", "Sophia",
            "Daniel", "Mia", "Matthew", "Ava", "Joseph", "Isabella", "Andrew", "Mason", "Jacob", "Ella",
            "Ethan", "Liam", "Alexander", "Benjamin", "Lucas", "Henry", "Samuel", "Jackson", "Sebastian", "Jack",
            "Owen", "Levi", "Ryan", "Lucas", "Oliver", "Ella", "Hannah", "Grace", "Victoria", "Amelia",
            "Chloe", "Lily", "Addison", "Riley", "Zoey", "Aubrey", "Scarlett", "Layla", "Harper", "Mila",
            "Noah", "Aiden", "Elijah", "Evelyn", "Aria", "Lillian", "Nora", "Penelope", "Riley", "Zoey",
            "Savannah", "Ariana", "Aurora", "Stella", "Paisley", "Hazel", "Nova", "Brooklyn", "Violet", "Skylar",
            "Camila", "Samantha", "Alyssa", "Leah", "Audrey", "Lucy", "Ellie", "Claire", "Natalie", "Sadie",
            "Ruby", "Anna", "Bella", "Naomi", "Eva", "Alice", "Ariana", "Cora", "Piper", "Quinn"
    };

    private static final String[] ITEMS = {
            "Chair", "Table", "Lamp", "Pen", "Notebook", "Book",
            "Umbrella", "Glasses", "Watch", "Coffee Mug", "Dress",
            "Toothbrush", "Mirror", "Backpack", "Shoes", "Hat",
            "Jacket", "Bicycle", "Sofa", "Pillow", "Blanket",
            "Towel", "Cup", "Plate", "Fork", "Spoon", "Knife",
            "Clock", "Painting", "Shelf", "Bag", "Wallet",
            "Key", "Scissors", "Fan", "Desk", "Globe", "Vase",
            "Sketchbook", "Speaker", "Pencil", "Eraser", "Ruler",
            "Paintbrush", "Canvas", "Watercolor", "Sketchpad",
            "Easel", "Palette", "Bottle", "Bowl", "Basket",
            "Curtains", "Plant", "Tablecloth", "Napkin",
            "Cutting Board", "Spatula", "Pan", "Pot", "Rolling Pin",
            "Salt Shaker", "Pepper Grinder", "Apron", "Glove",
            "Helmet", "Scarf", "Belt", "Gloves", "Boots",
            "Slippers", "Sandals", "Cushion", "Mat", "Rug",
            "Bed", "Dresser", "Wardrobe", "Frame", "Picture",
            "Poster", "Map", "Diary", "Calendar", "Envelope",
            "Stamp", "Brush", "Comb", "Shampoo", "Soap",
            "Tissue", "Box", "Basketball", "Soccer Ball",
            "Tennis Racket", "Yoga Mat", "Skipping Rope",
            "Fishing Rod", "Tent", "Sleeping Bag", "Lantern"
    };
    private static final Object[][] QUESTIONS_AND_ANSWERS = {
            {"Is the Earth round?", true},
            {"Is the sun a star?", true},
            {"Is 2 + 2 equal to 4?", true},
            {"Is water composed of hydrogen and oxygen?", true},
            {"Is Paris the capital of France?", true},
            {"Is 10 greater than 5?", true},
            {"Is a leap year every 4 years?", true},
            {"Is the square root of 9 equal to 3?", true},
            {"Is 7 a prime number?", true},
            {"Is the Great Wall of China visible from space?", false},
            {"Is 5 times 6 equal to 30?", true},
            {"Is Mount Everest the tallest mountain in the world?", true},
            {"Is the boiling point of water 100 degrees Celsius?", true},
            {"Is the speed of light faster than the speed of sound?", true},
            {"Is the chemical symbol for gold Au?", true},
            {"Is the Amazon River the longest river in the world?", false},
            {"Is the human body made up of 206 bones?", true},
            {"Is 3 to the power of 2 equal to 9?", true},
            {"Is the capital of Japan Tokyo?", true},
            {"Is the largest planet in our solar system Jupiter?", true},
            {"Is a triangle with sides 3, 4, 5 a right triangle?", true},
            {"Is the chemical formula for table salt NaCl?", true},
            {"Is the moon made of cheese?", false},
            {"Is the freezing point of water 0 degrees Celsius?", true},
            {"Is the Pacific Ocean the largest ocean on Earth?", true},
            {"Is Albert Einstein known for the theory of relativity?", true},
            {"Is 1 kilogram equal to 1000 grams?", true},
            {"Is the Mona Lisa a famous painting by Vincent van Gogh?", false},
            {"Is light a form of energy?", true},
            {"Is a year on Mercury shorter than a year on Earth?", true},
            {"Is the capital of Australia Sydney?", false},
            {"Is the formula for calculating area of a circle πr²?", true},
            {"Is the smallest prime number 2?", true},
            {"Is the human brain the most complex organ in the body?", true},
            {"Is the Sahara the largest desert in the world?", false},
            {"Is a dolphin a mammal?", true},
            {"Is photosynthesis a process used by plants to make food?", true},
            {"Is the speed of sound in air approximately 343 meters per second?", true},
            {"Is the periodic table an arrangement of chemical elements?", true},
            {"Is the capital of Italy Rome?", true},
            {"Is a day on Venus longer than a year on Venus?", true},
            {"Is the primary language of Brazil Spanish?", false},
            {"Is the human heart located on the right side of the body?", false},
            {"Is the longest river in the United States the Mississippi River?", false},
            {"Is the speed of an electron slower than the speed of light?", true},
            {"Is the main component of the sun helium?", false},
            {"Is Mars known as the Red Planet?", true},
            {"Is the Eiffel Tower located in Berlin?", false},
            {"Is the chemical symbol for silver Ag?", true},
            {"Is the capital of Canada Toronto?", false}
    };
    private static final Object[][] WEAPONS = {
            {"Longsword", 16},
            {"Battle Axe", 18},
            {"Crossbow", 10},
            {"Warhammer", 12},
            {"Dagger", 14},
            {"Staff", 16},
            {"Mace", 18},
            {"Shortbow", 10},
            {"Spear", 18},
            {"Flail", 12},
            {"Halberd", 14},
            {"Scimitar", 6},
            {"Morningstar", 8},
            {"Rapier", 6},
            {"Glaive", 10},
            {"Claymore", 14},
            {"Quarterstaff", 6},
            {"Falchion", 10},
            {"Scythe", 12},
            {"Whip", 4},
            {"Katana", 10},
            {"Sling", 4},
            {"Trident", 28},
            {"Composite Bow", 12},
            {"Club", 6},
            {"Sickle", 6},
            {"Scorpion Whip", 8},
            {"Boomerang", 4},
            {"Pike", 10},
            {"Net", 2},
            {"Javelin", 26},
            {"Lance", 12},
            {"Throwing Axe", 8},
            {"War Scythe", 14},
            {"Shuriken", 14},
            {"Gauntlet", 4},
            {"Blowgun", 12},
            {"Harpoon", 10},
            {"Chakram", 18},
            {"Flamberg", 14},
            {"Sai", 6},
            {"Atlatl", 8},
            {"Guisarme", 12},
            {"Falx", 10},
            {"Composite Longbow", 12},
            {"Wakizashi", 8},
            {"Heavy Crossbow", 14},
            {"Gandasa", 10},
            {"Nunchaku", 6},
            {"Sword Breaker", 8},
            {"Nagamaki", 12},
            {"OneShot Sword", 1200},

    };
    private static final Object[][] MONSTERS = {
            {"Goblin", 10, 4},
            {"Orc", 20, 8},
            {"Skeleton", 15, 6},
            {"Giant Spider", 25, 10},
            {"Troll", 30, 12},
            {"Zombie", 18, 7},
            {"Werewolf", 35, 14},
            {"Ogre", 40, 16},
            {"Wraith", 25, 10},
            {"Dragon", 50, 20},
            {"Vampire", 30, 12},
            {"Gargoyle", 25, 10},
            {"Harpy", 20, 8},
            {"Minotaur", 40, 16},
            {"Banshee", 30, 12},
            {"Cyclops", 45, 18},
            {"Ghost", 20, 8},
            {"Hydra", 60, 24},
            {"Lich", 35, 14},
            {"Manticore", 40, 16},
            {"Sphinx", 30, 12},
            {"Wight", 25, 10},
            {"Yeti", 35, 14},
            {"Basilisk", 30, 12},
            {"Chimera", 50, 20},
            {"Djinn", 40, 16},
            {"Griffin", 45, 18},
            {"Kobold", 12, 5},
            {"Lizardfolk", 18, 7},
            {"Mimic", 20, 8},
            {"Naga", 25, 10},
            {"Pixie", 10, 4},
            {"Roc", 50, 20},
            {"Satyr", 15, 6},
            {"Treant", 40, 16},
            {"Umber Hulk", 35, 14},
            {"Vargouille", 20, 8},
            {"Worg", 25, 10},
            {"Xorn", 30, 12},
            {"Yuan-ti", 40, 16},
            {"Zaratan", 60, 24},
            {"Aboleth", 50, 20},
            {"Beholder", 45, 18},
            {"Centaur", 30, 12},
            {"Doppelganger", 25, 10},
            {"Ettin", 40, 16},
            {"Flumph", 10, 4},
            {"Gelatinous Cube", 20, 8},
            {"Hook Horror", 25, 10},
            {"Intellect Devourer", 30, 12},
            {"Kuo-Toa", 35, 14},
            {"Lamia", 40, 16},
    };



    public static String generateRandomName() {
        return NAMES[RANDOM.nextInt(NAMES.length)];
    }
    public static String generateRandomItem() {
        return ITEMS[RANDOM.nextInt(ITEMS.length)];
    }
    public static Object[][] getRandomQuestions() {
        return QUESTIONS_AND_ANSWERS;
    }
    public static Object[] getRandomMonster() {
        return MONSTERS[RANDOM.nextInt(MONSTERS.length)];
    }
    public static Object[] getRandomWeapon() {
        return WEAPONS[RANDOM.nextInt(WEAPONS.length)];
    }


}
